title: "Dhruv Suthar"
description: "Learner · Developer · Designer"

url: https://unorderedlist.ml
baseurl: /

plugins_dir:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 8
  offset: 0
  permalink: '/pages/:num/'
  title: ':title :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

plugins:
  - jekyll-admin
  - jekyll-paginate
  - jekyll-paginate-v2

dirs:
  tags: "/tags/"
  categories: "/categories/"

github:
  repo: https://github.com/unorderedlist/

author:
  name: "Dhruv Suthar"
  url: "https://dhruvsuthar.ml/"
  donate: "https://donate.dhruvsuthar.ml/"

markdown: kramdown

include: ["_pages"]
exclude: [vendor]
